update build_book workflow file

diff --git a/.github/workflows/build_book.yml b/.github/workflows/build_book.yml
--- a/.github/workflows/build_book.yml
+++ b/.github/workflows/build_book.yml
@@ -34,18 +34,25 @@ jobs:
         id: read_config
         run: |
           JSON_FILE="$CONFIG_PATH"
-          if [ -f "JSON_FILE" ]; then
-            echo "CONFIG_PATH=$CONFIG_PATH"
-            JSON_CONTENT=$(cat "$JSON_FILE")
-            # JSON_CONTENT="${JSON_CONTENT//'%'/'%25'}"
-            # JSON_CONTENT="${JSON_CONTENT//$'\n'/'%0A'}"
-            # JSON_CONTENT="${JSON_CONTENT//$'\r'/'%0D'}"
-            echo "LANGUAGES=${JSON_CONTENT.languages}" >> $GITHUB_ENV
-            echo "::set-output name=JSON_CONTENT::$JSON_CONTENT";
-          else 
-            echo "JSON file not found at $CONFIG_PATH"
-            exit 1
-          fi
+          JSON_CONTENT=$(cat "$JSON_FILE")
+          # JSON_CONTENT="${JSON_CONTENT//'%'/'%25'}"
+          # JSON_CONTENT="${JSON_CONTENT//$'\n'/'%0A'}"
+          # JSON_CONTENT="${JSON_CONTENT//$'\r'/'%0D'}"
+          echo "LANGUAGES=${JSON_CONTENT.languages}" >> $GITHUB_ENV
+          echo "::set-output name=JSON_CONTENT::$JSON_CONTENT";
+          JSON_FILE="$CONFIG_PATH"
+          # if [ -f "JSON_FILE" ]; then
+          #   echo "CONFIG_PATH=$CONFIG_PATH"
+          #   JSON_CONTENT=$(cat "$JSON_FILE")
+          #   # JSON_CONTENT="${JSON_CONTENT//'%'/'%25'}"
+          #   # JSON_CONTENT="${JSON_CONTENT//$'\n'/'%0A'}"
+          #   # JSON_CONTENT="${JSON_CONTENT//$'\r'/'%0D'}"
+          #   echo "LANGUAGES=${JSON_CONTENT.languages}" >> $GITHUB_ENV
+          #   echo "::set-output name=JSON_CONTENT::$JSON_CONTENT";
+          # else 
+          #   echo "JSON file not found at $CONFIG_PATH"
+          #   exit 1
+          # fi
 
       - name: Use CONFIG variables from file
         run: |
