update build_book workflow file

diff --git a/.github/workflows/build_book.yml b/.github/workflows/build_book.yml
--- a/.github/workflows/build_book.yml
+++ b/.github/workflows/build_book.yml
@@ -34,13 +34,13 @@ jobs:
         id: read_config
         run: |
           JSON_FILE=$CONFIG_PATH
-        if [ -f "JSON_FILE"]: then
-          JSON_CONTENT=$(cat $JSON_FILE)
-          echo "::set-output name=json_content::$JSON_CONTENT"
-        else 
-          echo "JSON file not found at $CONFIG_PATH"
-          exit 1
-        fi
+          if [ -f "JSON_FILE"]: then
+            JSON_CONTENT=$(cat $JSON_FILE)
+            echo "::set-output name=json_content::$JSON_CONTENT"
+          else 
+            echo "JSON file not found at $CONFIG_PATH"
+            exit 1
+          fi
 
       - name: Use CONFIG variables from file
         run: |
